name: Mirror to GitVerse and GitFlic

on:
  push:
    branches: [ main ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitVerse
        run: |
          git remote add gitverse https://gitverse.ru/bylka2W/bylka2W.git || true
          git config --global url."https://${{ secrets.GITVERSE_USER }}:${{ secrets.GITVERSE_TOKEN }}@gitverse.ru/".insteadOf "https://gitverse.ru/"
          git push gitverse main --force

      - name: Push to GitFlic
        run: |
          git remote add gitflic https://gitflic.ru/project/bylka2w/bylka2w.git || true
          git config --global url."https://${{ secrets.GITFLIC_USER }}:${{ secrets.GITFLIC_TOKEN }}@gitflic.ru/".insteadOf "https://gitflic.ru/"
          git push gitflic main --force